version: "3.8"

services:
  app:
    container_name: knyapp_api
    image: knyapi:1.0.0
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    environment:
      - DB_URL=jdbc:mysql://db:3306/knydb
      - DB_USERNAME=root
      - DB_PASSWORD=password
  db:
    container_name: knyapi_db
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: knydb
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
